### ISSUE TITLE
ZSH as default, Node installs to bash

### ISSUE THREAD

**Issue by jwalsh2NU** [WhitewaterFoundry/Pengwin#461]
**Describe the bug**
Installed ZSH as the dafault shell, using pengwin-setup installs tools into bash.

**To Reproduce**
install zsh via pengwin-setup, set as default
install nodjs etc...  

**Expected behavior**
node to be added to zsh since it was default

**Screenshots**
Output:

 jwalsh2@surprise  node --version
zsh: command not found: node

 ✘ jwalsh2@surprise  bash
jwalsh2@surprise:~$ node --version
v12.2.0
jwalsh2@surprise:~$

**Additional context**

I think that after you install zsh as the default shell, pengwin-setup still assumes you have bash.  I have seem similar comments in Issues for FISH.

**Comment by Biswa96** [comment]
Try `zsh --login`. Any change?

**Comment by Biswa96** [comment]
I tried zsh+nodejs in Ubuntu:

1. Edit `/etc/passwd` file:

```
john:x:1000:1000:,,,:/home/john:/bin/zsh
root:x:0:0:root:/root:/bin/zsh
```

2. Command:

```bash
#https://github.com/nodesource/distributions/blob/master/README.md
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
apt install nodejs
```

**Comment by jwalsh2NU** [comment]
Thanks @Biswa96.  Agreed if I install nodejs outside of pengwin-setup I do get the expected behavior.  I was noting that the problem exists when you use pengwin-setup to install and setup zsh as default, then add other tools they do not always get added to the .zshrc -- looks like some scripts assume .bashrc.

Thanks for testing!

**Comment by bushidocodes** [comment]
I think this might be a more widespread issue. I recently used `pengwin-setup` to setup zsh, restarted the shell, and then used `pengwin-setup` to install python. It seemed to update the bash files just as you describe, so I had to manually modify my zshrc as well.

**Comment by crramirez** [comment]
This should fix this problem with ZSH and Node:

https://github.com/WhitewaterFoundry/pengwin-setup/pull/167

**Comment by deanhtid** [comment]
This still doesn't work. I installed zsh and ohmyzsh first. Rebooted the terminal and installed n through pengwin setup and still it adds the path to .bashrc and not zsh

**Comment by crramirez** [comment]
We will check following your steps.
