### ISSUE TITLE
There are a problem with update / upgrade via command line.

### ISSUE THREAD

**Issue by Jack31071973** [WhitewaterFoundry/Pengwin#770]
If you run sudo apt update you will get the following result:

`jack3173@LAPTOP-P9C2E5RE:~$ sudo apt update
[sudo] password for jack3173:
Hit:1 https://deb.debian.org/debian stable InRelease
Get:2 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
Hit:3 https://deb.debian.org/debian stable-updates InRelease
Hit:4 https://dl.google.com/linux/chrome/deb stable InRelease
Hit:5 https://deb.nodesource.com/node_14.x bullseye InRelease
Hit:6 https://deb.debian.org/debian-security stable-security InRelease
Hit:7 https://deb.debian.org/debian bookworm-backports InRelease
Hit:8 https://packages.microsoft.com/repos/microsoft-debian-bullseye-prod bullseye InRelease
Hit:9 https://deb.debian.org/debian oldstable InRelease
Hit:10 https://deb.debian.org/debian testing InRelease
Hit:11 https://packagecloud.io/whitewaterfoundry/pengwin-base/debian bookworm InRelease
Hit:12 https://packagecloud.io/whitewaterfoundry/pengwin-setup/debian bookworm InRelease
Hit:13 https://packagecloud.io/whitewaterfoundry/wslu/debian bullseye InRelease
Fetched 17.1 kB in 5s (3,672 B/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
9 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: https://dl.yarnpkg.com/debian/dists/stable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: https://deb.nodesource.com/node_14.x/dists/bullseye/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: https://packagecloud.io/whitewaterfoundry/pengwin-base/debian/dists/bookworm/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: https://packagecloud.io/whitewaterfoundry/pengwin-setup/debian/dists/bookworm/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: https://packagecloud.io/whitewaterfoundry/wslu/debian/dists/bullseye/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
N: Repository 'Debian bookworm' changed its 'non-free component' value from 'non-free' to 'non-free non-free-firmware'
N: More information about this can be found online in the Release notes at: https://www.debian.org/releases/bookworm/amd64/release-notes/ch-information.html#non-free-split`

Is it normal?

**Comment by crramirez** [comment]
Yes, glad you asked. The baseline of Pengwin changed to Debian 12. The announcement is comming.

Run the following:

```bash
pengwin-setup update
pengwin-setup update # yes twice
sudo apt dist-upgrade -y
sudo apt autoremove -y
```

**Comment by Jack31071973** [comment]
Here:
`jack3173@LAPTOP-P9C2E5RE:~$ pengwin-setup update
Just update packages
Updating package database
Running upgrade check...
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
jack3173@LAPTOP-P9C2E5RE:~$ pengwin-setup update
Just update packages
Updating package database
Running upgrade check...
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
jack3173@LAPTOP-P9C2E5RE:~$ sudo apt dist-upgrade -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
jack3173@LAPTOP-P9C2E5RE:~$ sudo apt autoremove -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
jack3173@LAPTOP-P9C2E5RE:~$`

Here:

`jack3173@LAPTOP-P9C2E5RE:~$ sudo apt update
Hit:1 https://deb.debian.org/debian stable InRelease
Hit:2 https://deb.debian.org/debian stable-updates InRelease
Hit:3 https://deb.debian.org/debian-security stable-security InRelease
Get:4 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
Hit:5 https://deb.debian.org/debian bookworm-backports InRelease
Hit:6 https://dl.google.com/linux/chrome/deb stable InRelease
Hit:7 https://deb.debian.org/debian oldstable InRelease
Hit:8 https://deb.nodesource.com/node_14.x bullseye InRelease
Hit:9 https://deb.debian.org/debian testing InRelease
Hit:10 https://packages.microsoft.com/repos/microsoft-debian-bullseye-prod bullseye InRelease
Hit:11 https://packagecloud.io/whitewaterfoundry/pengwin-base/debian bookworm InRelease
Hit:12 https://packagecloud.io/whitewaterfoundry/pengwin-setup/debian bookworm InRelease
Hit:13 https://packagecloud.io/whitewaterfoundry/wslu/debian bullseye InRelease
Fetched 17.1 kB in 4s (4,628 B/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
W: https://dl.yarnpkg.com/debian/dists/stable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: https://deb.nodesource.com/node_14.x/dists/bullseye/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: https://packagecloud.io/whitewaterfoundry/pengwin-base/debian/dists/bookworm/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: https://packagecloud.io/whitewaterfoundry/pengwin-setup/debian/dists/bookworm/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: https://packagecloud.io/whitewaterfoundry/wslu/debian/dists/bullseye/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
N: Repository 'Debian bookworm' changed its 'non-free component' value from 'non-free' to 'non-free non-free-firmware'
N: More information about this can be found online in the Release notes at: https://www.debian.org/releases/bookworm/amd64/release-notes/ch-information.html#non-free-split
jack3173@LAPTOP-P9C2E5RE:~$`

The packages are installed but there is some problem with the keyring. Do I need to fix it manually?
Thanks, in advance.

**Comment by crramirez** [comment]
Ok sorry I didn't read carefully your message. Yes, this is normal. The place to storage the gpg keys has changed. It is complaining that the keys are stored in the legacy place: `/etc/apt/trusted.gpg` for now there is no problem with that. We will update pengwin-setup to use the new place for the keys in each installer.

Changing it by hand is cumbersome.

**Comment by Jack31071973** [comment]
Ok thanks, anyway you solved one problem that some packages were not installed, now it is fine.

**Comment by crramirez** [comment]
Hello @Jack31071973 

We fixed the errors in Pengwin repositories that caused the warnings. Do a `pengwin-update update` then a `sudo apt update` to see the change.

The missing repo in your installation is the node 14 one. We are updating pengwin-setup to install the latest and lts versions 20 and 18 and the repos GPG keys in the newer way.

**Comment by Jack31071973** [comment]
@crramirez yes, it is working fine as you describe thanks.

**Comment by sgraf812** [comment]
Hi there, I'm having the exact same issue

```
Hit:1 https://deb.debian.org/debian stable InRelease
Hit:2 https://deb.debian.org/debian stable-updates InRelease
Hit:3 https://deb.debian.org/debian-security stable-security InRelease
Hit:4 https://packages.microsoft.com/repos/vscode stable InRelease
Hit:5 https://deb.debian.org/debian bookworm-backports InRelease
Hit:6 https://deb.debian.org/debian oldstable InRelease
Hit:7 https://deb.debian.org/debian testing InRelease
Hit:10 https://packagecloud.io/whitewaterfoundry/wslu/debian bullseye InRelease
Err:10 https://packagecloud.io/whitewaterfoundry/wslu/debian bullseye InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9009F03779A4CFA9
Get:8 https://packagecloud.io/whitewaterfoundry/pengwin-base/debian bookworm InRelease [26.1 kB]
Err:8 https://packagecloud.io/whitewaterfoundry/pengwin-base/debian bookworm InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B07B867FD74E3412
Get:9 https://packagecloud.io/whitewaterfoundry/pengwin-setup/debian bookworm InRelease [26.1 kB]
Err:9 https://packagecloud.io/whitewaterfoundry/pengwin-setup/debian bookworm InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 125DC4F7E4B50083
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://packagecloud.io/whitewaterfoundry/wslu/debian bullseye InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9009F03779A4CFA9
W: GPG error: https://packagecloud.io/whitewaterfoundry/pengwin-base/debian bookworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B07B867FD74E3412
E: The repository 'https://packagecloud.io/whitewaterfoundry/pengwin-base/debian bookworm InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://packagecloud.io/whitewaterfoundry/pengwin-setup/debian bookworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 125DC4F7E4B50083
E: The repository 'https://packagecloud.io/whitewaterfoundry/pengwin-setup/debian bookworm InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

I also tried the dist upgrade sequence in https://github.com/WhitewaterFoundry/Pengwin/issues/770#issuecomment-1632022583, to no avail.

I fixed it by following https://packagecloud.io/whitewaterfoundry/pengwin-setup/install#manual-deb, which I also did for the `pengwin-base` and `wslu` sources above. E.g.,

```
$ curl -fsSL https://packagecloud.io/whitewaterfoundry/wslu/gpgkey | gpg --dearmor | sudo tee /etc/apt/keyrings/whitewaterfoundry_wslu-archive-keyring.gpg
...
```
Etc. Compared to the instructions on the web page, I had to add the `.gpg` suffix, because that is where /etc/apt/sources.list.d/whitewaterfoundry.list` looked.

**Comment by crramirez** [comment]
I'll make some test to see if we can include a fix in pengwin-setup

**Comment by Jack31071973** [comment]
Hello @crramirez  I am still getting the following warning message, is it normal?
`W: https://deb.nodesource.com/node_14.x/dists/bullseye/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.`
