### ISSUE TITLE
Installing Kubernetes Tools from pengwin setup installs non-existent repository

### ISSUE THREAD

**Issue by j-0-h-n** [WhitewaterFoundry/Pengwin#786]
**Describe the bug**

**To Reproduce**
1. run pengwin-setup
2. install kubernetes tools
3. run apt-update

root@Umbriel:/home/john# apt update
Hit:1 https://deb.debian.org/debian stable InRelease
Get:2 https://deb.debian.org/debian stable-updates InRelease [55.4 kB]
Hit:3 https://deb.debian.org/debian-security stable-security InRelease
Get:4 https://deb.debian.org/debian bookworm-backports InRelease [56.5 kB]
Hit:5 https://packages.microsoft.com/repos/azure-cli bullseye InRelease
Hit:6 https://deb.debian.org/debian oldstable InRelease
Hit:7 https://packages.microsoft.com/repos/microsoft-debian-bullseye-prod bullseye InRelease
Ign:8 https://packages.cloud.google.com/apt kubernetes-xenial InRelease
Err:9 https://packages.cloud.google.com/apt kubernetes-xenial Release
  404  Not Found [IP: 142.250.187.206 443]
Hit:10 https://packagecloud.io/whitewaterfoundry/pengwin-base/debian bookworm InRelease
Hit:11 https://packagecloud.io/whitewaterfoundry/pengwin-setup/debian bookworm InRelease
Hit:12 https://packagecloud.io/whitewaterfoundry/wslu/debian bullseye InRelease
Reading package lists... Done
E: The repository 'https://apt.kubernetes.io kubernetes-xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

cat /etc/apt/sources.list.d/kubernetes.list
deb https://apt.kubernetes.io/ kubernetes-xenial main

**Expected behavior**
this should use the new repositories a guide to manual setup can be found here:
https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/#how-to-migrate-deb

**Screenshots**

**Additional context**

What other troubleshooting have you attempted?
I have followed the intructions on the link above and it fixes the problem but presumably the pengwin-setup tool should get it correct in the first place

Insert here:

**Pengwin Version**

Run `grep "PENGWIN_VERSION" /etc/os-release` in Pengwin.
24.03

**WSL general info**

Run `wslsys` in Pengwin.

Release Install Date: Sun Aug 20 23:24:55 BST 2023
Branch: ni_release
Build: 22621
Full Build: 22621.1.amd64fre.ni_release.220506-1250
Display Scaling: 1.5
Locale (Windows): en_GB
Theme (Windows): light
Uptime (Windows): 0d 2h 42m
Version (WSL): 2
Uptime (WSL): 0d 0h 52m
Release: Pengwin
Kernel: Linux 5.15.146.1-microsoft-standard-WSL2
Packages: 883
IPv4 Address: 172.29.25.193
System Type (Windows): Desktop
SystemD Status: disabled

**Comment by crramirez** [comment]
Thanks a lot for reporting. We will fix the installer

**Comment by crramirez** [comment]
Fixed in Pengwin version 24.08.x

**Comment by Kounavi** [comment]
Hello @crramirez . Has this fixed? I am using PENGWIN_VERSION="24.08.2" but this issue still occurs!

**Comment by crramirez** [comment]
Yes it should. Could you please paste the log here? You can call `pengwin-setup --debug` for more details.
